# Generated by Django 4.2.1 on 2023-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_task_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
