# Generated by Django 4.2.1 on 2023-05-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_task_is_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
