# Generated by Django 4.2.1 on 2023-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_task_options_alter_task_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delete_image',
            field=models.FileField(blank=True, null=True, upload_to='tasks/delete_image/'),
        ),
        migrations.AddField(
            model_name='task',
            name='edit_image',
            field=models.FileField(blank=True, null=True, upload_to='tasks/edit_image/'),
        ),
    ]
