# Generated by Django 4.2.1 on 2023-05-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
